name: Docker Step Failed Notification

on:
  workflow_run:
    workflows: ["CI / CD - Development","CI / CD - Production"]
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Failure Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_HOST }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USER }}
          password: ${{ secrets.MAIL_PASS }}
          to: ${{ secrets.TEAM_EMAILS }}
          subject: "CI Pipeline Failed for ${{ github.event.workflow_run.name }}"
          body: "The CI pipeline for workflow '${{ github.event.workflow_run.name }}' has failed. Please check the details at ${{ github.event.workflow_run.html_url }}."

